spring:
  application:
    name: standalone-eureka
  
server:
  port: ${PORT:8761}

---
spring:
  profiles: cloud
 
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/